### ISSUE TITLE
how to remove the greeting message properly?

### ISSUE THREAD

**Issue by ronylee11** [oh-my-fish/theme-fishbone#12]
![image](https://user-images.githubusercontent.com/64385071/154784894-6cc2b488-7742-465b-b577-315079340922.png)

I've removed ~/.local/share/omf/themes/fishbone/functions/fish_greeting.fish
but it somehow messes up the right prompt for the first line, once i pressed enter it turns back normal

![image](https://user-images.githubusercontent.com/64385071/154784982-5b57c946-ade7-46ed-a1be-2676014fd3de.png)

**Comment by scorphus** [comment]
Maybe there's still a `fish_greeting` function being defined? The following command can tell us that:

```
functions fish_greeting
```

Or that may be the result of a `$fish_greeting` variable still messing around. Let's check for that with:

```
set -S fish_greeting
echo $fish_greeting
```

**Comment by ronylee11** [comment]
tried removing all the fish_greeting files after running functions fish_greeting, still no clue
ran the command to check $fish_greeting, it returns $fish_greeting: set in universal scope, unexported, with 0 elements

i think the issue must be related to gnome-terminal, it worked as intended on konsole, alacritty and kitty
initially i thought it might be the gnome-terminal's font size messing up the right prompt, changed the font size from 14 to 12, still doesnt work
i was initializing gnome-terminal from a custom shortcut Alt + T binds to command line gnome-terminal --full-screen, tried removed the --full-screen parameter and voila! it worked as intended
so i think the issue here should be related to gnome-terminal, where their --full-screen parameter somehow messes up the right prompt,
i might've just move away from gnome-terminal and start using kitty!
thanks for the reply! have a nice day ^-^
